### ISSUE TITLE
Error with hassos 3.7

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [hassio-addons/addon-adb#19] opened 2019-12-22 17:27 UTC
Since the upgrade to hassos 3.7 the adb add on fails to start with the error

error: could not install *smartsocket* listener: Address already in use

This happens only after a full system reboot. 

Restarting the add on after everything is running does not yield this error and add on starts just fine. 

## Expected behavior
With hassos 2 the adb plugin started without problems after a full system reboot

## Actual behavior

After a full system reboot adb bridge reports running but its not really running and adb devices are not working and the error mentioned above is in the logs. 

## Steps to reproduce

Install the addon under hassos 3.7 and reboot the whole system

**Comment by renecloosterman** [comment] 2020-01-02 13:06
I have exactly the same problemen on 3.7, 

When installing ADB 
https://github.com/hassio-addons/addon-adb

All works well, intil i rebooted. Then came this error. 
Before i was on OS 2.8, and all worked well. 



[14:14:53] INFO: Connecting to device: 192.168.120.136...
already connected to 192.168.120.136:5555
[14:14:53] INFO: Starting the Android Debug Bridge server...
error: could not install *smartsocket* listener: Address already in use
[14:14:54] INFO: Starting the Android Debug Bridge server...
error: could not install *smartsocket* listener: Address already in use
[14:14:55] INFO: Starting the Android Debug Bridge server...
error: could not install *smartsocket* listener: Address already in use
[14:14:56] INFO: Starting the Android Debug Bridge server...
error: could not install *smartsocket* listener: Address already in use



<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-adb">hassio-addons/addon-adb</a></strong></div><div>Android Debug Bridge - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-adb</div></blockquote>

**Comment by frenck** [comment] 2020-01-04 23:19
I've installed it on HassOS 3.7 (2 different instances) but cannot reproduce it... 😞

**Comment by renecloosterman** [comment] 2020-01-05 14:12
No problem, is works now, but alter a HASSOS reset (full) , i have to restart the ADB service. Then all works fine again. 

If i have more info, i wil let you know.

**Comment by tofuSCHNITZEL** [comment] 2020-01-06 15:31
Since it only happens on a hassos restart I guess its some form of race condition - maybe with other addons.
I have the following addons installed: (maybe @renecloosterman you have some of them also?)

- ADB - Android Debug Bridge
- Almond
- AppDaemon
- Caddy Proxy
- Configurator
- ESPHome
- Hey Ada!
- Home Panel
- Mopidy
- Mosquitto broker
- SSH Server
- Samba Share
- TasmoAdmin
- motionEye

**Comment by renecloosterman** [comment] 2020-01-06 18:22
I have these ones ;-) 

ADB - Android Debug Bridge
Configurator
SSH Server
Samba Share

**Comment by tofuSCHNITZEL** [comment] 2020-01-06 18:26
okay, then maybe one of them block "smartsocket port" on boot.
@frenck: what is the "smartsocket listener: Address already in use"?

**Comment by sinclairpaul** [comment] 2020-01-06 21:18
The error you see means the port is already being used, so the service cannot start, as this is purely listening in the container, it is slightly confusing. 

Form the logs posted:

`[14:14:53] INFO: Connecting to device: 192.168.120.136...
already connected to 192.168.120.136:5555
[14:14:53] INFO: Starting the Android Debug Bridge server...
error: could not install smartsocket listener: Address already in use`

It is almost as if the service is being started twice, but this doesn't make sense.  Can you also check the supervisor logs for errors.

**Comment by sinclairpaul** [comment] 2020-01-06 21:21
Just to add, looking at the setup, these messages shouldn't appear in this order.  I am wondering if it may be wise to change the `# Wait for ADB to become available
s6-svwait -u -t 5000 /var/run/s6/services/adb` to be the port?

**Comment by frenck** [comment] 2020-02-25 21:39
Closing issue because of #20

**Closed as completed by frenck** 2020-02-25 21:39 UTC
